#!/bin/bash

# This script will check error logs for the last 1 hour

# Get the current time
current_time=$(date +%s)

# Calculate the time 1 hour ago
one_hour_ago=$((current_time - 3600))

# Format the time 1 hour ago for use in the find command
formatted_time=$(date -d @$one_hour_ago +"%Y-%m-%d %T")

# Find all files modified in the last 1 hour
find /var/log -type f -newermt "$formatted_time" -exec grep -H "error" {} \;
